theme: jekyll-theme-slate
title: Nick Ealesâ€™ blog
description: Hoping to save someone some time (including myself)
show_excerpts: true
disqus_shortname : "nickealesblog"
repo: "nickeales/nickeales.github.io"
baseurl: "nickeales.github.io"
